name: Bug Report
description: File an bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - carlitoplatanito
body:
  - type: textarea
    attributes:
      label: "What's Wrong?"
      description: A concise description of what the bug or problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'How can we fix it?'
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to the home page...
        1. Click on **This Button**...
        1. Type '...'
        1. See error in console...
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What devices amp; browser are you seeing the problem on?
      multiple: true
      options:
        - iOS (Mobile)
        - Android (Mobile)
        - Windows (Desktop)
        - MacOS (Desktop)
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
